export const ROUTES = {
  ORIGIN: "/",
  AUTH: "/auth",
  DASHBOARD: "/dashboard",
  USERS: "/users",
  GAMES: "/games",
  CREATE_GAME: "/games/create",
  UPDATE_GAME: "/games/update/:id",
  CALENDER: "/calender",
  TASKS: "/tasks",
  CREATE_TASK: "/tasks/create",
  UPDATE_TASK: "/tasks/update/:id",
  SETTINGS: "/settings",
  UNAUTHORIZED: "/unauthorized",
  MAPS: "/maps",
  TAGS: "/tags",
  PUZZLES: "/puzzles",
  GAME_ACTIVATION: "/game-activation",
  PLAYER_ADMIN: "/player-admin",
  NOT_FOUND: "*",
};
